server:
  port: 8080

spring:
  application:
    name: spring-security

  datasource:
    driver-class-name: org.postgresql.Driver
    url: { DB_URL }
    username: { DB_USERNAME }
    password: { DB_PASSWORD }

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
